// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CryptoAccouting
{
	public partial class AboutViewConroller : UIViewController
	{
		public AboutViewConroller (IntPtr handle) : base (handle)
		{
		}
	}
}
