// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CoinBalance.Base.lproj
{
	public partial class LeveragePLViewController : UIViewController
	{
		public LeveragePLViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
